-- Create the user_journeys table needed by GAELP
CREATE TABLE IF NOT EXISTS `aura-thrive-platform.gaelp_data.user_journeys` (
    journey_id STRING NOT NULL,
    user_id STRING NOT NULL,
    canonical_user_id STRING NOT NULL,
    journey_start TIMESTAMP NOT NULL,
    journey_end TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    timeout_at TIMESTAMP,
    initial_state STRING,
    current_state STRING,
    final_state STRING,
    state_progression JSON,
    converted BOOLEAN DEFAULT FALSE,
    conversion_timestamp TIMESTAMP,
    conversion_value FLOAT64,
    conversion_type STRING,
    first_touch_channel STRING,
    last_touch_channel STRING,
    touchpoint_count INT64 DEFAULT 0,
    days_to_conversion INT64,
    journey_score FLOAT64 DEFAULT 0.0,
    engagement_score FLOAT64 DEFAULT 0.0,
    intent_score FLOAT64 DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Create the user_profiles table
CREATE TABLE IF NOT EXISTS `aura-thrive-platform.gaelp_data.user_profiles` (
    user_id STRING NOT NULL,
    canonical_user_id STRING NOT NULL,
    device_ids ARRAY<STRING>,
    email_hash STRING,
    phone_hash STRING,
    fingerprint_hash STRING,
    ip_address STRING,
    age_range STRING,
    gender STRING,
    location_country STRING,
    location_region STRING,
    location_city STRING,
    current_journey_state STRING,
    journey_score FLOAT64 DEFAULT 0.0,
    conversion_probability FLOAT64 DEFAULT 0.0,
    first_seen TIMESTAMP,
    last_seen TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Create the journey_touchpoints table
CREATE TABLE IF NOT EXISTS `aura-thrive-platform.gaelp_data.journey_touchpoints` (
    touchpoint_id STRING NOT NULL,
    journey_id STRING NOT NULL,
    user_id STRING NOT NULL,
    canonical_user_id STRING NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    channel STRING NOT NULL,
    campaign_id STRING,
    creative_id STRING,
    placement_id STRING,
    interaction_type STRING DEFAULT 'impression',
    page_url STRING,
    referrer_url STRING,
    device_type STRING,
    browser STRING,
    os STRING,
    content_category STRING,
    message_variant STRING,
    audience_segment STRING,
    targeting_criteria JSON,
    pre_state STRING,
    post_state STRING,
    state_change_confidence FLOAT64,
    dwell_time_seconds FLOAT64,
    scroll_depth FLOAT64,
    click_depth INT64,
    engagement_score FLOAT64,
    first_touch_weight FLOAT64 DEFAULT 0.0,
    last_touch_weight FLOAT64 DEFAULT 0.0,
    time_decay_weight FLOAT64 DEFAULT 0.0,
    position_weight FLOAT64 DEFAULT 0.0,
    linear_weight FLOAT64 DEFAULT 0.0,
    data_driven_weight FLOAT64 DEFAULT 0.0,
    interaction_quality_score FLOAT64 DEFAULT 0.0,
    bid_amount FLOAT64,
    win_rate FLOAT64,
    ctr_prediction FLOAT64,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Create competitor_exposures table
CREATE TABLE IF NOT EXISTS `aura-thrive-platform.gaelp_data.competitor_exposures` (
    exposure_id STRING NOT NULL,
    journey_id STRING NOT NULL,
    user_id STRING NOT NULL,
    canonical_user_id STRING NOT NULL,
    competitor_id STRING NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    channel STRING,
    estimated_bid FLOAT64,
    won BOOLEAN,
    estimated_message STRING,
    estimated_spend FLOAT64,
    impact_on_journey FLOAT64,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);