#!/bin/bash

echo "🚀 GAELP Setup Continuation Script"
echo "=================================="
echo ""
echo "VM has been restarted with full GCP access!"
echo ""

# Test that we now have full access
echo "✅ Testing GCP access..."
gcloud services list --enabled --filter="name:bigquery.googleapis.com" --format="value(name)" && echo "✓ BigQuery access confirmed" || echo "✗ BigQuery access failed"

echo ""
echo "📋 Next steps to complete GAELP setup:"
echo ""
echo "1. Enable required APIs:"
echo "   gcloud services enable bigquery.googleapis.com storage.googleapis.com pubsub.googleapis.com aiplatform.googleapis.com"
echo ""
echo "2. Create BigQuery dataset:"
echo "   bq mk --dataset --location=us-central1 aura-thrive-platform:gaelp_training"
echo ""
echo "3. Create Cloud Storage bucket:"
echo "   gsutil mb -l us-central1 gs://gaelp-model-checkpoints-$(date +%s)"
echo ""
echo "4. Set up environment variables in /home/hariravichandran/AELP/.env:"
echo "   - OPENAI_API_KEY or ANTHROPIC_API_KEY"
echo "   - GOOGLE_CLOUD_PROJECT=aura-thrive-platform"
echo "   - BIGQUERY_DATASET=gaelp_training"
echo "   - GCS_BUCKET=gaelp-model-checkpoints-XXX"
echo ""
echo "5. Install any missing Python packages:"
echo "   pip install google-cloud-bigquery google-cloud-storage google-cloud-pubsub"
echo ""
echo "Ready to continue? Run these commands or let Claude help you!"